name: Rust

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test:
    uses: fpco/reusable_workflows/.github/workflows/rust_build_lint_test.yml@rust
    with:
      binary: juno-node-exporter
      package: juno-node-exporter
      build_version_location: "build-version.txt"
    secrets:
      git_credential: "https://abc:def@github.com"

  docker:
    runs-on: ubuntu-latest
    needs: [build_lint_test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: juno-node-exporter
          path: target/x86_64-unknown-linux-musl/release/
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: .buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/fpco-internal/juno-node-exporter:${{ github.sha }}
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache-new
      - name: Cache Rotation
        run: |
          rm -rf .buildx-cache
          mv .buildx-cache-new .buildx-cache
